import Head from "next/head";
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from "../components/sharedstyles";
import Cards from "../components/cards";
import { useState } from "react";

export default function Home() {
  const [urlValue, setUrlValue] = useState<string>(
    "https://za.theater/events/lostandfound"
  );

  return (
    // <Container>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <Main>
    //     <Title>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </Title>

    //     <Description>
    //       Get started by editing
    //       <CodeTag>pages/index.tsx</CodeTag>
    //     </Description>

    //     <Cards />
    //   </Main>
    // </Container>
    <>
      <Head>
        <title>iframeをためす</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input
        type="url"
        style={{
          minWidth: "100%",
        }}
        defaultValue={urlValue}
        onBlur={(value) => {
          setUrlValue(value.target.value);
        }}
      />

      <div
        style={{
          height: "100vh",
        }}
      >
        <iframe
          src={urlValue}
          style={{
            height: "100%",
            width: "100%",
          }}
        ></iframe>
      </div>
    </>
  );
}
